[workspace]
members = [
    "src/common",
    "src/cli-crusty",
    "src/heapstore",
    "src/memstore",
    "src/server",
    "src/txn_manager",
    "src/optimizer",
    "src/queryexe",
    "src/utilities",
]
exclude = [
    "e2e-benchmarks",
    "e2e-tests",
]
